/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiParseRouteImport } from './routes/api/parse'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiRechargeStatusRouteImport } from './routes/api/recharge/status'
import { Route as ApiRechargeProductsRouteImport } from './routes/api/recharge/products'
import { Route as ApiRechargeCreateRouteImport } from './routes/api/recharge/create'
import { Route as ApiPublicXunhupayNotifyRouteImport } from './routes/api/public/xunhupay-notify'
import { Route as ApiPublicMediaStreamRouteImport } from './routes/api/public/media-stream'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiRechargeStatusRoute = ApiRechargeStatusRouteImport.update({
  id: '/api/recharge/status',
  path: '/api/recharge/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRechargeProductsRoute = ApiRechargeProductsRouteImport.update({
  id: '/api/recharge/products',
  path: '/api/recharge/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRechargeCreateRoute = ApiRechargeCreateRouteImport.update({
  id: '/api/recharge/create',
  path: '/api/recharge/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXunhupayNotifyRoute = ApiPublicXunhupayNotifyRouteImport.update({
  id: '/api/public/xunhupay-notify',
  path: '/api/public/xunhupay-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaStreamRoute = ApiPublicMediaStreamRouteImport.update({
  id: '/api/public/media-stream',
  path: '/api/public/media-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/config': typeof ApiConfigRoute
  '/api/parse': typeof ApiParseRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/media-stream': typeof ApiPublicMediaStreamRoute
  '/api/public/xunhupay-notify': typeof ApiPublicXunhupayNotifyRoute
  '/api/recharge/create': typeof ApiRechargeCreateRoute
  '/api/recharge/products': typeof ApiRechargeProductsRoute
  '/api/recharge/status': typeof ApiRechargeStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/config': typeof ApiConfigRoute
  '/api/parse': typeof ApiParseRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/media-stream': typeof ApiPublicMediaStreamRoute
  '/api/public/xunhupay-notify': typeof ApiPublicXunhupayNotifyRoute
  '/api/recharge/create': typeof ApiRechargeCreateRoute
  '/api/recharge/products': typeof ApiRechargeProductsRoute
  '/api/recharge/status': typeof ApiRechargeStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/config': typeof ApiConfigRoute
  '/api/parse': typeof ApiParseRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/media-stream': typeof ApiPublicMediaStreamRoute
  '/api/public/xunhupay-notify': typeof ApiPublicXunhupayNotifyRoute
  '/api/recharge/create': typeof ApiRechargeCreateRoute
  '/api/recharge/products': typeof ApiRechargeProductsRoute
  '/api/recharge/status': typeof ApiRechargeStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/config'
    | '/api/parse'
    | '/api/public/media-proxy'
    | '/api/public/media-stream'
    | '/api/public/xunhupay-notify'
    | '/api/recharge/create'
    | '/api/recharge/products'
    | '/api/recharge/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/config'
    | '/api/parse'
    | '/api/public/media-proxy'
    | '/api/public/media-stream'
    | '/api/public/xunhupay-notify'
    | '/api/recharge/create'
    | '/api/recharge/products'
    | '/api/recharge/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/api/config'
    | '/api/parse'
    | '/api/public/media-proxy'
    | '/api/public/media-stream'
    | '/api/public/xunhupay-notify'
    | '/api/recharge/create'
    | '/api/recharge/products'
    | '/api/recharge/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiParseRoute: typeof ApiParseRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicMediaStreamRoute: typeof ApiPublicMediaStreamRoute
  ApiPublicXunhupayNotifyRoute: typeof ApiPublicXunhupayNotifyRoute
  ApiRechargeCreateRoute: typeof ApiRechargeCreateRoute
  ApiRechargeProductsRoute: typeof ApiRechargeProductsRoute
  ApiRechargeStatusRoute: typeof ApiRechargeStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/recharge/status': {
      id: '/api/recharge/status'
      path: '/api/recharge/status'
      fullPath: '/api/recharge/status'
      preLoaderRoute: typeof ApiRechargeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recharge/products': {
      id: '/api/recharge/products'
      path: '/api/recharge/products'
      fullPath: '/api/recharge/products'
      preLoaderRoute: typeof ApiRechargeProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recharge/create': {
      id: '/api/recharge/create'
      path: '/api/recharge/create'
      fullPath: '/api/recharge/create'
      preLoaderRoute: typeof ApiRechargeCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xunhupay-notify': {
      id: '/api/public/xunhupay-notify'
      path: '/api/public/xunhupay-notify'
      fullPath: '/api/public/xunhupay-notify'
      preLoaderRoute: typeof ApiPublicXunhupayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-stream': {
      id: '/api/public/media-stream'
      path: '/api/public/media-stream'
      fullPath: '/api/public/media-stream'
      preLoaderRoute: typeof ApiPublicMediaStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiParseRoute: ApiParseRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicMediaStreamRoute: ApiPublicMediaStreamRoute,
  ApiPublicXunhupayNotifyRoute: ApiPublicXunhupayNotifyRoute,
  ApiRechargeCreateRoute: ApiRechargeCreateRoute,
  ApiRechargeProductsRoute: ApiRechargeProductsRoute,
  ApiRechargeStatusRoute: ApiRechargeStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
